name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Deno
        run: |
          DENO_VERSION="$(cat DENO_VERSION)"
          curl -fsSL https://deno.land/x/install/install.sh | sh -s "$DENO_VERSION"
          echo "PATH=$HOME/.deno/bin:$PATH" >> "$GITHUB_ENV"

      - name: Check the expectations file is sorted
        run: ./scripts/sort_expectations.ts --check

      - name: Run test suite
        run: ./runner.ts --only-print-failures
