name: update-test262

on:
  schedule:
    # Every Monday at 12 AM UTC.
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  update-test262:
    name: Update test262
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Needed to run ./scripts/cleanup_expectations.ts
      - name: Setup Deno
        run: |
          DENO_VERSION="$(cat DENO_VERSION)"
          curl -fsSL https://deno.land/x/install/install.sh | sh -s "$DENO_VERSION"
          echo "$HOME/.deno/bin" >> "$GITHUB_PATH"

      - name: Update and commit
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
          git config --global user.email "90636620+andreubot@users.noreply.github.com"
          git config --global user.name "andreubot"
          git config --global user.signingkey "1D165DD908A9C331"

          cd test262
          OLD_SHA="$(git rev-parse HEAD)"
          git fetch
          git reset --hard origin/main
          NEW_SHA="$(git rev-parse HEAD)"
          cd ..
          if [ "$OLD_SHA" != "$NEW_SHA" ]; then
            BRANCH_NAME="update-test262/$(date -u +%d-%m-%y)"
            PR_TITLE="Update test262 ($(date -u "+%h %d %Y"))"
            git checkout -b "$BRANCH_NAME"
            git add test262
            git commit -m "$PR_TITLE"
            ./scripts/cleanup_expectations.ts
            if [ "$(git diff --name-only)" != "" ]; then
              git add expectations.json
              git commit -m "Clean up expectations"
            fi

            git push -u origin "$BRANCH_NAME"
            gh pr create --title "$PR_TITLE" --body "" --draft \
              --assignee andreubotella --label update-test262
          fi
        env:
          GH_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.BOT_GPG_SIGNING_KEY }}
