name: update-deno

on:
  schedule:
    # Every day at 12 AM UTC.
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  update-deno:
    name: Update Deno
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_GH_TOKEN }}
          submodules: recursive

      - name: Setup Deno (previous version)
        run: |
          DENO_VERSION="$(cat DENO_VERSION)"
          curl -fsSL https://deno.land/x/install/install.sh | sh -s "$DENO_VERSION"
          echo "$HOME/.deno/bin" >> "$GITHUB_PATH"

      - name: Update if needed
        id: update
        shell: deno run --allow-read=. --allow-write=. --allow-net {0}
        run: |
          const VERSION_FILE = "./DENO_VERSION";
          const VERSIONS_URL = "https://raw.githubusercontent.com/denoland/deno_website2/main/versions.json";

          const versions = await fetch(VERSIONS_URL).then(res => res.json());
          const currentVersion = (await Deno.readTextFile(VERSION_FILE)).trim();
          const latestVersion = versions.cli[0].trim();

          if (currentVersion !== latestVersion) {
            await Deno.writeTextFile(VERSION_FILE, latestVersion);
            console.log("::set-output name=updated::true");
          } else {
            console.log("::set-output name=updated::false");
          }

      - name: Commit update
        if: ${{ steps.update.outputs.updated == 'true' }}
        run: |
          git config --global user.email "90636620+andreubot@users.noreply.github.com"
          git config --global user.name "andreubot"

          BRANCH_NAME="update-deno/$(cat ./DENO_VERSION)"
          PR_TITLE="Update Deno to $(cat ./DENO_VERSION)"
          git checkout -b "$BRANCH_NAME"
          git add ./DENO_VERSION
          git commit -m "$PR_TITLE"

          git push -u origin "$BRANCH_NAME"
          gh pr create --title "$PR_TITLE" --body "" --draft \
            --assignee andreubotella --label update-deno
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GH_TOKEN }}
